apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
      - name: hadoop
        image: cloudsuite/hadoop:latest
        ports:
        - containerPort: 8088 # Example port, adjust based on your needs
